CREATE TABLE friends
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    note        VARCHAR(500),
    deleted     BOOLEAN      DEFAULT FALSE              NOT NULL,
    created_at  TIMESTAMP    DEFAULT NOW()              NOT NULL,
    updated_at  TIMESTAMP,
    created_by  VARCHAR(50)  DEFAULT 'SYSTEM'           NOT NULL,
    updated_by  VARCHAR(255),
    version     BIGINT       DEFAULT 0                  NOT NULL,
    sender_id   BIGINT                                  NOT NULL,
    received_id BIGINT                                  NOT NULL,
    sender_note VARCHAR(500),
    status      VARCHAR(100) DEFAULT 'ANONYMOUSE'       NOT NULL,
    CONSTRAINT pk_friends PRIMARY KEY (id)
);

CREATE TABLE tags
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    note       VARCHAR(500),
    deleted    BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at TIMESTAMP   DEFAULT NOW()               NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by VARCHAR(255),
    version    BIGINT      DEFAULT 0                   NOT NULL,
    tag_code   VARCHAR(50)                             NOT NULL,
    tag_name   VARCHAR(200)                            NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (id)
);

ALTER TABLE tags
    ADD CONSTRAINT uc_tags_tag_code UNIQUE (tag_code);

ALTER TABLE tags
    ADD CONSTRAINT uc_tags_tag_name UNIQUE (tag_name);