CREATE TABLE user_roles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    note       VARCHAR(500),
    deleted    BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at TIMESTAMP   DEFAULT NOW()               NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by VARCHAR(255),
    version    BIGINT      DEFAULT 0                   NOT NULL,
    role_code  VARCHAR(50)                             NOT NULL,
    role_name  VARCHAR(200)                            NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    note       VARCHAR(500),
    deleted    BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at TIMESTAMP   DEFAULT NOW()               NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by VARCHAR(255),
    version    BIGINT      DEFAULT 0                   NOT NULL,
    user_id    VARCHAR(50)                             NOT NULL,
    full_name  VARCHAR(200)                            NOT NULL,
    sex        VARCHAR(100)                            NOT NULL,
    birth_date date                                    NOT NULL,
    phone      VARCHAR(30)                             NOT NULL,
    address    VARCHAR(300),
    avatar     VARCHAR(300),
    user_name  VARCHAR(100)                            NOT NULL,
    email      VARCHAR(300)                            NOT NULL,
    password   VARCHAR(300)                            NOT NULL,
    verified   BOOLEAN     DEFAULT FALSE               NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE user_roles
    ADD CONSTRAINT uc_user_roles_role_code UNIQUE (role_code);

ALTER TABLE user_roles
    ADD CONSTRAINT uc_user_roles_role_name UNIQUE (role_name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone UNIQUE (phone);

ALTER TABLE users
    ADD CONSTRAINT uc_users_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_user_name UNIQUE (user_name);