plugins {
    id("io.micronaut.library") version "4.5.4"
    id("com.gradleup.shadow") version "8.3.7"
    id("io.micronaut.test-resources") version "4.5.4"
    id("maven-publish")
}

version = "1.0.0"
group = "io.universechat.app"

repositories {
    mavenCentral()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            groupId = 'io.universechat.app'
            artifactId = 'library-core'
            version = '1.0.0'
        }
    }
}

dependencies {
    annotationProcessor("io.micronaut.data:micronaut-data-processor")
    annotationProcessor("io.micronaut:micronaut-http-validation")
    annotationProcessor("io.micronaut.serde:micronaut-serde-processor")
    annotationProcessor("io.micronaut.validation:micronaut-validation-processor")
    annotationProcessor "org.projectlombok:lombok:1.18.24"
    annotationProcessor "io.micronaut:micronaut-inject-java"
    implementation("io.minio:minio:8.6.0")
    implementation("com.ongres.scram:client:2.1")
    implementation("io.micrometer:context-propagation")
    implementation("io.micronaut.data:micronaut-data-hibernate-reactive")
    implementation("io.micronaut.reactor:micronaut-reactor")
    implementation("io.micronaut.serde:micronaut-serde-jackson")
    implementation("io.micronaut.validation:micronaut-validation")
    implementation("io.micronaut:micronaut-http-server")
    implementation("io.micronaut:micronaut-runtime")
    implementation("io.vertx:vertx-pg-client")
    implementation("jakarta.validation:jakarta.validation-api")
    compileOnly("io.micronaut:micronaut-http-client")
    compileOnly 'org.projectlombok:lombok:1.18.24'
    runtimeOnly("ch.qos.logback:logback-classic")
    testImplementation("io.micronaut:micronaut-http-client")
    testResourcesService("org.postgresql:postgresql")
}

java {
    sourceCompatibility = JavaVersion.toVersion("21")
    targetCompatibility = JavaVersion.toVersion("21")
}

graalvmNative.toolchainDetection = false

micronaut {
    testRuntime("junit5")
    processing {
        incremental(true)
        annotations("io.universechat.app.*")
    }
    testResources {
        additionalModules.add("hibernate-reactive-postgresql")
        enabled = false
    }
}