CREATE TABLE group_member_roles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY      NOT NULL,
    note       VARCHAR(500),
    deleted    BOOLEAN                     DEFAULT FALSE    NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()    NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(50)                 DEFAULT 'SYSTEM' NOT NULL,
    updated_by VARCHAR(255),
    version    BIGINT                      DEFAULT 0        NOT NULL,
    role_name  VARCHAR(100)                                 NOT NULL,
    color_code VARCHAR(50)                                  NOT NULL,
    CONSTRAINT pk_group_member_roles PRIMARY KEY (id)
);

CREATE TABLE group_members
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY      NOT NULL,
    note                 VARCHAR(500),
    deleted              BOOLEAN                     DEFAULT FALSE    NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()    NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    created_by           VARCHAR(50)                 DEFAULT 'SYSTEM' NOT NULL,
    updated_by           VARCHAR(255),
    version              BIGINT                      DEFAULT 0        NOT NULL,
    group_id             BIGINT                                       NOT NULL,
    user_id              BIGINT                                       NOT NULL,
    group_member_role_id BIGINT                                       NOT NULL,
    group_member_status  VARCHAR(255)                                 NOT NULL,
    CONSTRAINT pk_group_members PRIMARY KEY (id)
);

CREATE TABLE groups
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY      NOT NULL,
    note        VARCHAR(500),
    deleted     BOOLEAN                     DEFAULT FALSE    NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()    NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    created_by  VARCHAR(50)                 DEFAULT 'SYSTEM' NOT NULL,
    updated_by  VARCHAR(255),
    version     BIGINT                      DEFAULT 0        NOT NULL,
    title       VARCHAR(100)                                 NOT NULL,
    owner_id    BIGINT                                       NOT NULL,
    description VARCHAR(500),
    avatar      VARCHAR(500),
    CONSTRAINT pk_groups PRIMARY KEY (id)
);

ALTER TABLE group_members
    ADD CONSTRAINT FK_GROUP_MEMBERS_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE group_members
    ADD CONSTRAINT FK_GROUP_MEMBERS_ON_GROUP_MEMBER_ROLE FOREIGN KEY (group_member_role_id) REFERENCES group_member_roles (id);